# Generated by Django 3.0.5 on 2020-04-19 07:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_auto_20200417_2141"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("h1", models.TextField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("python_skill", models.IntegerField(blank=True, null=True)),
                ("django_skill", models.IntegerField(blank=True, null=True)),
                ("html_skill", models.IntegerField(blank=True, null=True)),
                ("seo_skill", models.IntegerField(blank=True, null=True)),
                ("present_activities", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Main Page",},
        ),
    ]
