# Generated by Django 3.0.8 on 2020-08-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='inst_login',
        ),
    ]
