# Generated by Django 3.0.8 on 2020-08-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorin', '0003_auto_20200814_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramphoto',
            name='dominant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramphoto',
            name='palette',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='dominant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='palette',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='inst_biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
