# Generated by Django 3.0.8 on 2020-08-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorin', '0004_auto_20200815_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramphoto',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='inst_profile_pic_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
