# Generated by Django 3.1 on 2020-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorin', '0005_auto_20200815_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramphoto',
            name='similar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
