# Generated by Django 3.1 on 2020-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorin', '0006_instagramphoto_similar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_name', models.TextField(blank=True, null=True)),
                ('palette', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='emoji_match_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
