default:
  ALLOWED_HOSTS: []
  AWS_ACCESS_KEY_ID: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SITE_ID: 0
  INST_USERNAME: ""
  INST_PASSWORD: ""

development:
  AWS_S3_REGION_NAME: "us-east-1"
  SECRET_KEY: ""
  DEBUG: true
  SITE_ID: 2
  INST_USERNAME: ""
  INST_PASSWORD: ""

heroku:
  AWS_S3_REGION_NAME: "us-east-1"
  ALLOWED_HOSTS:
    - .colorin.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: false
  SITE_ID: 2
  SECRET_KEY: ""
  INST_USERNAME: ""
  INST_PASSWORD: ""

test:
  EMAIL_FROM: "test@test.name"
  DEBUG: 1
  SECRET_KEY: "1"
  SITE_ID: 2


travis:
  EMAIL_FROM: "test@test.name"
  DEBUG: 1
  SECRET_KEY: "1"
  SITE_ID: 2
