# Generated by Django 3.0.5 on 2020-04-28 11:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="preview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
