# Generated by Django 3.0.8 on 2020-08-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='inst_login',
        ),
    ]
