# Generated by Django 3.0.5 on 2020-04-19 12:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("h1", models.TextField(blank=True, null=True)),
                ("block", models.TextField(blank=True, null=True)),
                ("article", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Resume Page",},
        ),
    ]
