# Generated by Django 3.0.5 on 2020-04-22 20:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_auto_20200420_2117"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project", options={"verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="responsibility", options={"verbose_name_plural": "Responsibilities"},
        ),
        migrations.AlterModelOptions(
            name="technology", options={"verbose_name_plural": "Technologies"},
        ),
        migrations.AddField(
            model_name="project",
            name="achievements_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
